### ISSUE TITLE
[JS] Build failure - Couldn't find preset "jolt" relative to directory

### ISSUE THREAD

**Issue by ylac** [negativetwelve/react-native-heap-analytics#3] opened 2017-08-01 01:41 UTC
Hi,

I'm having an issue after upgrading from heap-analytics 0.2.0 to 1.1.2. On build I get the error: "TransformError: /Users/[user]/Desktop/spot-save/node_modules/react-native-heap-analytics/build/Heap.js: Couldn't find preset "jolt" relative to directory "/Users/[user]/Desktop/spot-save/node_modules/react-native-heap-analytics".

I've tried reinstalling the pod, and have also set the header search path to recursive. I'm on react-native 0.44.3. 

Any help would be greatly appreciated.

**Comment by negativetwelve** [comment] 2017-08-01 01:45
Hi @ylac, since the package is already transpiled, it shouldn't be using the babel config. Can you try resetting the packager cache? I'll update the package in our apps and see if I can reproduce this

**Comment by ylac** [comment] 2017-08-01 01:47
Hi @negativetwelve, yeah I tried resetting the packager cache but it didn't help. I just reverted to 1.0.0 and it builds ok. 

Btw, I think there's a typo in the docs, heap.event should be heap.track?

**Comment by negativetwelve** [comment] 2017-08-01 01:49
hmm okay I'll definitely get this babel issue fixed today.

Yeah, that's a typo, I can fix that as well (unless you want to submit a PR? :)

**Comment by ylac** [comment] 2017-08-01 01:54
Great thanks, I just submitted the PR (my first ever :) ).

**Comment by negativetwelve** [comment] 2017-08-01 02:04
Awesome, that's exciting :) thanks for contributing!

**Comment by negativetwelve** [comment] 2017-08-01 02:44
Looks like you stumbled on a pretty big react-native issue @ylac:

* https://github.com/developit/mitt/issues/31
* https://github.com/acdlite/change-emitter/issues/2

and the big one: https://github.com/facebook/react-native/issues/10966

I'll fix up the packages tonight (I just switched all of them to an "babel" key under package.json :(

thanks again for pointing this out!

**Comment by negativetwelve** [comment] 2017-08-01 07:05
This has been fixed and released as v1.3.0 https://github.com/negativetwelve/react-native-heap-analytics/releases/tag/1.3.0

**Closed as completed by negativetwelve** 2017-08-01 07:05 UTC
Labels: bug
